[versions]
gradleJavaConventions = "0.1.2"
gradlePluginPublish = "1.1.0"
jacoco = "0.8.8"
javaPoet = "1.13.0"
junit = "5.9.2"

[libraries]
javaPoet = { module = "com.squareup:javapoet", version.ref = "javaPoet" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
gradleJavaConventions = { id = "com.opencastsoftware.gradle.java-conventions", version.ref = "gradleJavaConventions" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }