[versions]
gradleBuildInfo = "0.3.1"
gradleJavaConventions = "0.1.4"
gradlePluginPublish = "1.2.1"
jacoco = "0.8.8"
javaPoet = "1.13.0"
junit = "5.10.0"

[libraries]
javaPoet = { module = "com.squareup:javapoet", version.ref = "javaPoet" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

[plugins]
gradleBuildInfo = { id = "com.opencastsoftware.gradle.buildinfo", version.ref = "gradleBuildInfo" }
gradleJavaConventions = { id = "com.opencastsoftware.gradle.java-conventions", version.ref = "gradleJavaConventions" }
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
