name: CI

on:
  push:
  pull_request:

env:
  ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.2.0
        with:
          java-version: 11
          distribution: temurin

      - name: Build & Test
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: build

      - name: Publish To Sonatype
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository

      - name: Publish To Gradle Plugin Portal
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: |
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
            publishPlugins
