name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SECRET }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Download Java JDK
        uses: typelevel/download-java@817e8c0d48dc2e88e155a8e4f69ba493bef621be # v2
        id: download-java
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Java JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: jdkfile
          java-version: 11
          jdkFile: ${{ steps.download-java.outputs.jdkFile }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4

      - name: Build & Test
        run: ./gradlew build --info

      - name: Publish Test Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: test-results
          path: '**/build/test-results/*/TEST-*.xml'

      - name: Publish To Sonatype
        if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
        run: ./gradlew publishAllPublicationsToMavenCentral

      - name: Publish To Gradle Plugin Portal
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/v')
        run: |
          ./gradlew \
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} \
            publishPlugins
