name: Test Report

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@07ab29fd4a977ae4d2b275087cf67563dfdf0295 # v9
        with:
          name: test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@62516aa379bff6370c95fd5894d5a27fb6619d9b # v5
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: "**/build/test-results/*/TEST-*.xml"
