name: Test Report

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@854e2de9396304899dbe03bf9995fd73533190d1 # v4
        with:
          name: test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@9379f0ccddcab154835d4e2487555ee79614fe95 # v4
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: "**/build/test-results/*/TEST-*.xml"
